$ENV{'TEXINPUTS'}='tex//:' . $ENV{'TEXINPUTS'};
$ENV{'T1FONTS'}='fonts/type1//:' . $ENV{'T1FONTS'};
$ENV{'AFMFONTS'}='fonts/afm//:' . $ENV{'AFMFONTS'};
$ENV{'TEXFONTMAPS'}='fonts/map//:' . $ENV{'TEXFONTMAPS'};
$ENV{'TFMFONTS'}='fonts/tfm//:' . $ENV{'TFMFONTS'};
$ENV{'TTFONTS'}='fonts/truetype//:' . $ENV{'TTFONTS'};
$ENV{'VFFONTS'}='fonts/vf//:' . $ENV{'VFFONTS'};
$ENV{'ENCFONTS'}='fonts/enc//:' . $ENV{'ENCFONTS'};
