ci:
  autoupdate_commit_msg: "chore(deps): update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: "^tests/packages/"
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: "^tests"

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2  # select the tag or revision you want, or run `pre-commit autoupdate`
    hooks:
    - id: autopep8

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    - id: isort

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.11.10
  #   hooks:
  #     - id: ruff
  #       types_or: [python, pyi, jupyter]
  #       args: [--fix, --ignore, T201, --ignore, E402]
  #     - id: ruff-format
  #       types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
        exclude: .pre-commit-config.yaml
      - id: disallow-expressions
        name: Disallow expressions
        language: pygrep
        entry: tool\.cmake
        exclude: .pre-commit-config.yaml
